package com.DiscordBot.KotlinDiscordBot.coin.util

enum class Market(
    val code: String,
    val koreanName: String,
    val englishName: String
) {
    KRW_BTC("KRW-BTC", "비트코인", "Bitcoin"),
    KRW_ETH("KRW-ETH", "이더리움", "Ethereum"),
    KRW_ETC("KRW-ETC", "이더리움 클래식", "Ethereum Classic"),
    KRW_XRP("KRW-XRP", "엑스알피 [리플]", "XRP"),
    KRW_BCH("KRW-BCH", "비트코인 캐시", "Bitcoin Cash"),
    KRW_QTUM("KRW-QTUM", "퀀텀", "Qtum"),
    KRW_A("KRW-A", "볼타", "Vaulta"),
    KRW_ICX("KRW-ICX", "아이콘", "ICON"),
    KRW_TRX("KRW-TRX", "트론", "TRON"),
    KRW_ELF("KRW-ELF", "엘프", "aelf"),
    KRW_KNC("KRW-KNC", "카이버 네트워크", "Kyber Network"),
    KRW_GLM("KRW-GLM", "골렘", "Golem"),
    KRW_ZIL("KRW-ZIL", "질리카", "Zilliqa"),
    KRW_WAXP("KRW-WAXP", "왁스", "WAXP"),
    KRW_POWR("KRW-POWR", "파워렛저", "Powerledger"),
    KRW_LRC("KRW-LRC", "루프링", "Loopring"),
    KRW_STEEM("KRW-STEEM", "스팀", "Steem"),
    KRW_ZRX("KRW-ZRX", "제로엑스", "0x"),
    KRW_SNT("KRW-SNT", "스테이터스네트워크토큰", "Status Network"),
    KRW_ADA("KRW-ADA", "에이다", "Cardano"),
    KRW_CTXC("KRW-CTXC", "코르텍스", "Cortex"),
    KRW_BAT("KRW-BAT", "베이직어텐션토큰", "Basic Attention Token"),
    KRW_THETA("KRW-THETA", "쎄타토큰", "Theta Token"),
    KRW_CVC("KRW-CVC", "시빅", "Civic"),
    KRW_WAVES("KRW-WAVES", "웨이브", "Waves"),
    KRW_LINK("KRW-LINK", "체인링크", "ChainLink"),
    KRW_ENJ("KRW-ENJ", "엔진코인", "Enjin Coin"),
    KRW_VET("KRW-VET", "비체인", "VeChain"),
    KRW_MTL("KRW-MTL", "메탈", "Metal"),
    KRW_IOST("KRW-IOST", "이오스트", "IOST"),
    KRW_AMO("KRW-AMO", "아모코인", "AMO Coin"),
    KRW_BSV("KRW-BSV", "비트코인에스브이", "BITCOINSV"),
    KRW_ORBS("KRW-ORBS", "오브스", "Orbs"),
    KRW_TFUEL("KRW-TFUEL", "쎄타퓨엘", "TFUEL"),
    KRW_ANKR("KRW-ANKR", "앵커", "Ankr Network"),
    KRW_MIX("KRW-MIX", "믹스마블", "MixMarvel Token"),
    KRW_CRO("KRW-CRO", "크로노스", "Cronos"),
    KRW_CHR("KRW-CHR", "크로미아", "Chromia"),
    KRW_MBL("KRW-MBL", "무비블록", "MovieBloc"),
    KRW_FCT2("KRW-FCT2", "피르마체인", "Firmachain"),
    KRW_WOM("KRW-WOM", "왐토큰", "WOM Token"),
    KRW_BOA("KRW-BOA", "보아", "BOSagora"),
    KRW_MEV("KRW-MEV", "미버스", "MEVerse"),
    KRW_SXP("KRW-SXP", "솔라", "Solar"),
    KRW_COS("KRW-COS", "콘텐토스", "Contentos"),
    KRW_EL("KRW-EL", "엘리시아", "ELYSIA"),
    KRW_HIVE("KRW-HIVE", "하이브", "Hive"),
    KRW_XPR("KRW-XPR", "엑스피알 네트워크", "XPR Network"),
    KRW_EGG("KRW-EGG", "네스트리", "Nestree"),
    KRW_BORA("KRW-BORA", "보라", "BORA"),
    KRW_ARPA("KRW-ARPA", "알파", "ARPA"),
    KRW_CTC("KRW-CTC", "크레딧코인", "Creditcoin"),
    KRW_APM("KRW-APM", "에이피엠 코인", "apM Coin"),
    KRW_CKB("KRW-CKB", "너보스", "Nervos Network"),
    KRW_AERGO("KRW-AERGO", "아르고", "Aergo"),
    KRW_EVZ("KRW-EVZ", "이브이지", "Electronic Vehicle Zone"),
    KRW_QTCON("KRW-QTCON", "퀴즈톡", "Quiztok"),
    KRW_UNI("KRW-UNI", "유니스왑", "Uniswap"),
    KRW_YFI("KRW-YFI", "연파이낸스", "yearn.finance"),
    KRW_UMA("KRW-UMA", "우마", "UMA"),
    KRW_AAVE("KRW-AAVE", "에이브", "Aave"),
    KRW_COMP("KRW-COMP", "컴파운드", "Compound"),
    KRW_BAL("KRW-BAL", "밸런서", "Balancer"),
    KRW_RSR("KRW-RSR", "리저브라이트", "Reserve Rights"),
    KRW_NMR("KRW-NMR", "뉴메레르", "Numeraire"),
    KRW_RLC("KRW-RLC", "아이젝", "iExec RLC"),
    KRW_UOS("KRW-UOS", "울트라", "Ultra"),
    KRW_SAND("KRW-SAND", "샌드박스", "The Sandbox"),
    KRW_AWE("KRW-AWE", "에이더블유이", "AWE Network"),
    KRW_BEL("KRW-BEL", "벨라프로토콜", "Bella Protocol"),
    KRW_OBSR("KRW-OBSR", "옵저버", "Observer"),
    KRW_POLA("KRW-POLA", "폴라리스 쉐어", "Polaris Share"),
    KRW_ADP("KRW-ADP", "어댑터 토큰", "Adappter Token"),
    KRW_DVI("KRW-DVI", "디비전", "Dvision Network"),
    KRW_GHX("KRW-GHX", "게이머코인", "Gamercoin"),
    KRW_CBK("KRW-CBK", "코박토큰", "Cobak Token"),
    KRW_MVC("KRW-MVC", "마일벌스", "MileVerse"),
    KRW_BLY("KRW-BLY", "블로서리", "Blocery"),
    KRW_GRT("KRW-GRT", "더그래프", "The Graph"),
    KRW_BIOT("KRW-BIOT", "바이오패스포트", "BioPassport"),
    KRW_SNX("KRW-SNX", "신세틱스", "Synthetix Network Token"),
    KRW_SOFI("KRW-SOFI", "라이파이낸스", "Rai Finance"),
    KRW_GRACY("KRW-GRACY", "그레이시", "Gracy"),
    KRW_OXT("KRW-OXT", "오키드", "Orchid"),
    KRW_MAPO("KRW-MAPO", "맵프로토콜", "MAP Protocol"),
    KRW_AQT("KRW-AQT", "알파쿼크", "Alpha Quark Token"),
    KRW_WIKEN("KRW-WIKEN", "위드", "Project WITH"),
    KRW_CTSI("KRW-CTSI", "카르테시", "Cartesi"),
    KRW_MANA("KRW-MANA", "디센트럴랜드", "Decentraland"),
    KRW_LPT("KRW-LPT", "라이브피어", "Livepeer"),
    KRW_SUSHI("KRW-SUSHI", "스시스왑", "Sushiswap"),
    KRW_PUNDIX("KRW-PUNDIX", "펀디엑스", "Pundi X"),
    KRW_CELR("KRW-CELR", "셀러네트워크", "Celer Network"),
    KRW_SLF("KRW-SLF", "셀프 체인", "Self Chain"),
    KRW_BFC("KRW-BFC", "바이프로스트", "Bifrost"),
    KRW_ALICE("KRW-ALICE", "마이네이버앨리스", "MyNeighborAlice"),
    KRW_OGN("KRW-OGN", "오리진프로토콜", "Origin Protocol"),
    KRW_COTI("KRW-COTI", "코티", "COTI"),
    KRW_CAKE("KRW-CAKE", "팬케이크스왑", "PancakeSwap"),
    KRW_BNT("KRW-BNT", "뱅코르", "Bancor"),
    KRW_XVS("KRW-XVS", "비너스", "Venus"),
    KRW_SWAP("KRW-SWAP", "트러스트스왑", "TrustSwap"),
    KRW_CHZ("KRW-CHZ", "칠리즈", "Chiliz"),
    KRW_AXS("KRW-AXS", "엑시인피니티", "Axie Infinity"),
    KRW_DAO("KRW-DAO", "다오메이커", "DAO Maker"),
    KRW_SIX("KRW-SIX", "식스", "SIX"),
    KRW_USDS("KRW-USDS", "유에스디에스", "USDS"),
    KRW_SHIB("KRW-SHIB", "시바이누", "SHIBA INU"),
    KRW_POL("KRW-POL", "폴리곤 에코시스템 토큰", "Polygon Ecosystem Token"),
    KRW_WOO("KRW-WOO", "우", "WOO"),
    KRW_ACH("KRW-ACH", "알케미페이", "Alchemy Pay"),
    KRW_XLM("KRW-XLM", "스텔라루멘", "Stellar Lumens"),
    KRW_ONT("KRW-ONT", "온톨로지", "Ontology"),
    KRW_META("KRW-META", "메타디움", "Metadium"),
    KRW_KAIA("KRW-KAIA", "카이아", "Kaia"),
    KRW_ONG("KRW-ONG", "온톨로지가스", "Ontology Gas"),
    KRW_ALGO("KRW-ALGO", "알고랜드", "Algorand"),
    KRW_JST("KRW-JST", "저스트", "JUST"),
    KRW_XTZ("KRW-XTZ", "테조스", "Tezos"),
    KRW_MLK("KRW-MLK", "밀크", "MiL.k"),
    KRW_DOT("KRW-DOT", "폴카닷", "Polkadot"),
    KRW_ATOM("KRW-ATOM", "코스모스", "Cosmos"),
    KRW_TEMCO("KRW-TEMCO", "템코", "TEMCO"),
    KRW_DOGE("KRW-DOGE", "도지코인", "Dogecoin"),
    KRW_KSM("KRW-KSM", "쿠사마", "Kusama"),
    KRW_CTK("KRW-CTK", "셴투", "Shentu"),
    KRW_BNB("KRW-BNB", "비앤비", "BNB"),
    KRW_NFT("KRW-NFT", "에이피이앤에프티", "APENFT"),
    KRW_SUN("KRW-SUN", "썬", "SUN"),
    KRW_XEC("KRW-XEC", "이캐시", "eCash"),
    KRW_SOL("KRW-SOL", "솔라나", "Solana"),
    KRW_EGLD("KRW-EGLD", "멀티버스엑스", "MultiversX"),
    KRW_MASK("KRW-MASK", "마스크네트워크", "Mask Network"),
    KRW_C98("KRW-C98", "코인98", "Coin98"),
    KRW_MED("KRW-MED", "메디블록", "MediBloc"),
    KRW_1INCH("KRW-1INCH", "1인치", "1inch"),
    KRW_CRV("KRW-CRV", "커브", "Curve DAO Token"),
    KRW_BOBA("KRW-BOBA", "보바토큰", "Boba Network"),
    KRW_DYDX("KRW-DYDX", "디와이디엑스", "dYdX"),
    KRW_MINA("KRW-MINA", "미나", "Mina"),
    KRW_FLOW("KRW-FLOW", "플로우", "Flow"),
    KRW_JOE("KRW-JOE", "트레이더 조", "JOE"),
    KRW_GALA("KRW-GALA", "갈라", "Gala"),
    KRW_ENS("KRW-ENS", "이더리움네임서비스", "Ethereum Name Service"),
    KRW_BTT("KRW-BTT", "비트토렌트", "BitTorrent"),
    KRW_JASMY("KRW-JASMY", "재스미코인", "JasmyCoin"),
    KRW_REQ("KRW-REQ", "리퀘스트", "Request"),
    KRW_CSPR("KRW-CSPR", "캐스퍼", "Casper"),
    KRW_AVAX("KRW-AVAX", "아발란체", "Avalanche"),
    KRW_TDROP("KRW-TDROP", "티드랍", "ThetaDrop"),
    KRW_HBAR("KRW-HBAR", "헤데라", "Hedera"),
    KRW_FANC("KRW-FANC", "팬시", "fanC"),
    KRW_MAY("KRW-MAY", "메이플라워", "Mayflower"),
    KRW_REI("KRW-REI", "레이", "REI"),
    KRW_T("KRW-T", "쓰레스홀드", "Threshold"),
    KRW_MBX("KRW-MBX", "마브렉스", "Marblex"),
    KRW_GMT("KRW-GMT", "스테픈", "STEPN"),
    KRW_TAVA("KRW-TAVA", "알타바", "ALTAVA"),
    KRW_D("KRW-D", "달 오픈 네트워크", "DAR Open Network"),
    KRW_APE("KRW-APE", "에이프코인", "ApeCoin"),
    KRW_WNCG("KRW-WNCG", "랩트 나인 크로니클 골드", "Wrapped NCG"),
    KRW_AL("KRW-AL", "아치루트", "ArchLoot"),
    KRW_XCN("KRW-XCN", "오닉스코인", "Onyxcoin"),
    KRW_AZIT("KRW-AZIT", "아지트", "Azit"),
    KRW_FLR("KRW-FLR", "플레어", "Flare"),
    KRW_SFP("KRW-SFP", "세이프팔", "Safepal"),
    KRW_FITFI("KRW-FITFI", "스텝앱", "Step App"),
    KRW_STAT("KRW-STAT", "스탯", "STAT"),
    KRW_CRTS("KRW-CRTS", "크라토스", "Cratos"),
    KRW_LBL("KRW-LBL", "레이블 에이아이", "Lable AI"),
    KRW_FLZ("KRW-FLZ", "펠라즈", "Fellaz"),
    KRW_LM("KRW-LM", "레저메타", "LeisureMeta"),
    KRW_GRND("KRW-GRND", "슈퍼워크", "Superwalk"),
    KRW_APT("KRW-APT", "앱토스", "Aptos"),
    KRW_BLUR("KRW-BLUR", "블러", "Blur"),
    KRW_OAS("KRW-OAS", "오아시스", "Oasys"),
    KRW_HOOK("KRW-HOOK", "훅트 프로토콜", "Hooked Protocol"),
    KRW_LWA("KRW-LWA", "루미웨이브", "Lumiwave"),
    KRW_OP("KRW-OP", "옵티미즘", "Optimism"),
    KRW_ROA("KRW-ROA", "로아코어", "ROA CORE"),
    KRW_GMX("KRW-GMX", "지엠엑스", "GMX"),
    KRW_STX("KRW-STX", "스택스", "Stacks"),
    KRW_XPLA("KRW-XPLA", "엑스플라", "XPLA"),
    KRW_AHT("KRW-AHT", "아하토큰", "AhaToken"),
    KRW_ARB("KRW-ARB", "아비트럼", "Arbitrum"),
    KRW_INJ("KRW-INJ", "인젝티브", "Injective"),
    KRW_HFT("KRW-HFT", "해시플로우", "Hashflow"),
    KRW_RPL("KRW-RPL", "로켓풀", "Rocket Pool"),
    KRW_IMX("KRW-IMX", "이뮤터블엑스", "Immutable X"),
    KRW_CFX("KRW-CFX", "콘플럭스", "Conflux Network"),
    KRW_ACS("KRW-ACS", "액세스프로토콜", "Access Protocol"),
    KRW_FXS("KRW-FXS", "프랙스 셰어", "Frax Share"),
    KRW_CELO("KRW-CELO", "셀로", "Celo"),
    KRW_LDO("KRW-LDO", "리도다오", "Lido DAO"),
    KRW_S("KRW-S", "소닉", "Sonic"),
    KRW_FET("KRW-FET", "페치", "Fetch.ai"),
    KRW_SUI("KRW-SUI", "수이", "SUI"),
    KRW_NCT("KRW-NCT", "폴리스웜", "Polyswarm"),
    KRW_FLOKI("KRW-FLOKI", "플로키", "FLOKI"),
    KRW_ALEX("KRW-ALEX", "알렉스", "ALEX Lab"),
    KRW_ID("KRW-ID", "스페이스 아이디", "SPACE ID"),
    KRW_RENDER("KRW-RENDER", "렌더토큰", "Render Token"),
    KRW_STG("KRW-STG", "스타게이트 파이낸스", "Stargate Finance"),
    KRW_OSMO("KRW-OSMO", "오스모시스", "Osmosis"),
    KRW_FIL("KRW-FIL", "파일코인", "Filecoin"),
    KRW_ILV("KRW-ILV", "일루비움", "Illuvium"),
    KRW_MAV("KRW-MAV", "매버릭 프로토콜", "Maverick Protocol"),
    KRW_RSS3("KRW-RSS3", "알에스에스쓰리", "RSS3"),
    KRW_AUDIO("KRW-AUDIO", "오디우스", "Audius"),
    KRW_AGI("KRW-AGI", "델리시움", "Delysium"),
    KRW_ASTR("KRW-ASTR", "아스타", "Astar"),
    KRW_WLD("KRW-WLD", "월드코인", "Worldcoin"),
    KRW_FLUX("KRW-FLUX", "플럭스", "Flux"),
    KRW_AGLD("KRW-AGLD", "어드벤처골드", "Adventure Gold"),
    KRW_AR("KRW-AR", "알위브", "Arweave"),
    KRW_RVN("KRW-RVN", "레이븐코인", "Ravencoin"),
    KRW_LEVER("KRW-LEVER", "레버파이", "LeverFi"),
    KRW_EDU("KRW-EDU", "오픈 캠퍼스", "Open Campus"),
    KRW_SEI("KRW-SEI", "세이", "Sei"),
    KRW_WAXL("KRW-WAXL", "엑셀라", "Axelar"),
    KRW_MOC("KRW-MOC", "모스코인", "Moss Coin"),
    KRW_PEPE("KRW-PEPE", "페페", "PEPE"),
    KRW_CYBER("KRW-CYBER", "사이버", "Cyber"),
    KRW_ARKM("KRW-ARKM", "아캄", "Arkham"),
    KRW_PYR("KRW-PYR", "불칸 포지드", "Vulcan Forged"),
    KRW_IOTX("KRW-IOTX", "아이오텍스", "IoTeX"),
    KRW_HIGH("KRW-HIGH", "하이스트리트", "Highstreet"),
    KRW_PENDLE("KRW-PENDLE", "펜들", "Pendle"),
    KRW_BICO("KRW-BICO", "바이코노미", "Biconomy"),
    KRW_STORJ("KRW-STORJ", "스토리지", "Storj"),
    KRW_API3("KRW-API3", "에이피아이쓰리", "API3"),
    KRW_ZTX("KRW-ZTX", "지티엑스", "ZTX"),
    KRW_MNT("KRW-MNT", "맨틀", "Mantle"),
    KRW_GTC("KRW-GTC", "깃코인", "Gitcoin"),
    KRW_METIS("KRW-METIS", "메티스다오", "MetisDAO"),
    KRW_TIA("KRW-TIA", "셀레스티아", "Celestia"),
    KRW_ICP("KRW-ICP", "인터넷 컴퓨터", "Internet Computer"),
    KRW_SPURS("KRW-SPURS", "토트넘 홋스퍼", "Tottenham Hotspur Fan Token"),
    KRW_NEO("KRW-NEO", "네오", "Neo"),
    KRW_GAS("KRW-GAS", "가스", "Gas"),
    KRW_BIGTIME("KRW-BIGTIME", "빅타임", "Big Time"),
    KRW_ZETA("KRW-ZETA", "제타체인", "ZetaChain"),
    KRW_GRS("KRW-GRS", "그로스톨코인", "Groestlcoin"),
    KRW_ARK("KRW-ARK", "아크", "Ark"),
    KRW_YGG("KRW-YGG", "일드길드게임즈", "Yield Guild Games"),
    KRW_HUNT("KRW-HUNT", "헌트", "Hunt Town"),
    KRW_KAVA("KRW-KAVA", "카바", "Kava"),
    KRW_MAGIC("KRW-MAGIC", "매직", "Magic"),
    KRW_AUCTION("KRW-AUCTION", "바운스토큰", "Bounce Token"),
    KRW_USDT("KRW-USDT", "테더", "Tether USDt"),
    KRW_USDC("KRW-USDC", "유에스디코인", "USD Coin"),
    KRW_RAD("KRW-RAD", "래드웍스", "Radworks"),
    KRW_LSK("KRW-LSK", "리스크", "Lisk"),
    KRW_TT("KRW-TT", "썬더코어", "ThunderCore"),
    KRW_ACE("KRW-ACE", "퓨저니스트", "Fusionist"),
    KRW_SKL("KRW-SKL", "스케일", "SKALE"),
    KRW_IQ("KRW-IQ", "아이큐", "IQ"),
    KRW_PYTH("KRW-PYTH", "피스 네트워크", "Pyth Network"),
    KRW_MANTA("KRW-MANTA", "만타 네트워크", "Manta Network"),
    KRW_AKT("KRW-AKT", "아카시 네트워크", "Akash Network"),
    KRW_BEAM("KRW-BEAM", "빔", "Beam"),
    KRW_JTO("KRW-JTO", "지토", "Jito"),
    KRW_JUP("KRW-JUP", "주피터", "Jupiter"),
    KRW_STRK("KRW-STRK", "스타크넷", "Starknet"),
    KRW_SC("KRW-SC", "시아코인", "Siacoin"),
    KRW_BONK("KRW-BONK", "봉크", "Bonk"),
    KRW_TOKAMAK("KRW-TOKAMAK", "토카막 네트워크", "Tokamak Network"),
    KRW_AIOZ("KRW-AIOZ", "아이오즈 네트워크", "AIOZ Network"),
    KRW_ZK("KRW-ZK", "지케이싱크", "zkSync"),
    KRW_ONDO("KRW-ONDO", "온도 파이낸스", "Ondo Finance"),
    KRW_ALT("KRW-ALT", "알트레이어", "AltLayer"),
    KRW_NEAR("KRW-NEAR", "니어프로토콜", "NEAR Protocol"),
    KRW_RON("KRW-RON", "로닌", "Ronin"),
    KRW_FIDA("KRW-FIDA", "솔라나 네임 서비스", "Solana Name Service"),
    KRW_STRAX("KRW-STRAX", "스트라티스", "Stratis"),
    KRW_XAI("KRW-XAI", "자이", "Xai"),
    KRW_W("KRW-W", "웜홀", "Wormhole"),
    KRW_POLYX("KRW-POLYX", "폴리매쉬", "Polymesh"),
    KRW_CORE("KRW-CORE", "코어", "Core"),
    KRW_BB("KRW-BB", "바운스빗", "BounceBit"),
    KRW_POKT("KRW-POKT", "포켓네트워크", "Pocket Network"),
    KRW_REZ("KRW-REZ", "렌조", "Renzo"),
    KRW_OMNI("KRW-OMNI", "옴니 네트워크", "Omni Network"),
    KRW_ENA("KRW-ENA", "에테나", "Ethena"),
    KRW_MOCA("KRW-MOCA", "모카네트워크", "Moca Network"),
    KRW_ETHFI("KRW-ETHFI", "이더파이", "ether.fi"),
    KRW_MEW("KRW-MEW", "캣인어독스월드", "cat in a dogs world"),
    KRW_ZRO("KRW-ZRO", "레이어제로", "LayerZero"),
    KRW_IO("KRW-IO", "아이오넷", "io.net"),
    KRW_BLAST("KRW-BLAST", "블라스트", "Blast"),
    KRW_TAIKO("KRW-TAIKO", "타이코", "Taiko"),
    KRW_BRETT("KRW-BRETT", "브렛", "Brett"),
    KRW_ATH("KRW-ATH", "에이셔", "Aethir"),
    KRW_PCI("KRW-PCI", "페이코인", "Paycoin"),
    KRW_AVAIL("KRW-AVAIL", "어베일", "Avail"),
    KRW_TON("KRW-TON", "톤코인", "Toncoin"),
    KRW_G("KRW-G", "그래비티", "Gravity"),
    KRW_LISTA("KRW-LISTA", "리스타 다오", "Lista DAO"),
    KRW_PEAQ("KRW-PEAQ", "피크", "peaq"),
    KRW_EIGEN("KRW-EIGEN", "아이겐레이어", "EigenLayer"),
    KRW_ORDER("KRW-ORDER", "오덜리 네트워크", "Orderly Network"),
    KRW_MERL("KRW-MERL", "멀린 체인", "Merlin Chain"),
    KRW_SCR("KRW-SCR", "스크롤", "Scroll"),
    KRW_SWELL("KRW-SWELL", "스웰 네트워크", "Swell Network"),
    KRW_UXLINK("KRW-UXLINK", "유엑스링크", "UXLINK"),
    KRW_SKY("KRW-SKY", "스카이 프로토콜", "Sky Protocol"),
    KRW_PONKE("KRW-PONKE", "폰케", "Ponke"),
    KRW_MVL("KRW-MVL", "엠블", "MVL"),
    KRW_CARV("KRW-CARV", "카브", "CARV"),
    KRW_PUFFER("KRW-PUFFER", "퍼퍼", "Puffer"),
    KRW_SUNDOG("KRW-SUNDOG", "썬도그", "Sundog"),
    KRW_TURBO("KRW-TURBO", "터보", "Turbo"),
    KRW_RAY("KRW-RAY", "레이디움", "Raydium"),
    KRW_SAFE("KRW-SAFE", "세이프", "Safe"),
    KRW_VIRTUAL("KRW-VIRTUAL", "버추얼 프로토콜", "Virtuals Protocol"),
    KRW_DRIFT("KRW-DRIFT", "드리프트", "Drift"),
    KRW_MOVE("KRW-MOVE", "무브먼트", "Movement"),
    KRW_F("KRW-F", "신퓨처스", "Synfutures"),
    KRW_DEEP("KRW-DEEP", "딥북", "DeepBook"),
    KRW_MORPHO("KRW-MORPHO", "모포", "Morpho"),
    KRW_NEIRO("KRW-NEIRO", "네이로", "Neiro"),
    KRW_MOODENG("KRW-MOODENG", "무뎅", "Moo Deng"),
    KRW_DBR("KRW-DBR", "디브릿지", "deBridge"),
    KRW_GOAT("KRW-GOAT", "고트세우스 막시무스", "Goatseus Maximus"),
    KRW_NIL("KRW-NIL", "닐리온", "Nillion"),
    KRW_ME("KRW-ME", "매직 에덴", "Magic Eden"),
    KRW_INIT("KRW-INIT", "이니시아", "Initia"),
    KRW_ZRC("KRW-ZRC", "저킷", "Zircuit"),
    KRW_IOTA("KRW-IOTA", "아이오타", "IOTA"),
    KRW_PENGU("KRW-PENGU", "펏지 펭귄", "Pudgy Penguins"),
    KRW_ACX("KRW-ACX", "어크로스 프로토콜", "Across Protocol"),
    KRW_AERO("KRW-AERO", "에어로드롬 파이낸스", "Aerodrome Finance"),
    KRW_THE("KRW-THE", "테나", "THENA"),
    KRW_AMP("KRW-AMP", "앰프", "Amp"),
    KRW_VANA("KRW-VANA", "바나", "Vana"),
    KRW_XYO("KRW-XYO", "엑스와이오", "XYO"),
    KRW_A8("KRW-A8", "에인션트8", "Ancient8"),
    KRW_SONIC("KRW-SONIC", "소닉 에스브이엠", "Sonic SVM"),
    KRW_WIF("KRW-WIF", "도그위프햇", "dogwifhat"),
    KRW_IP("KRW-IP", "스토리", "Story"),
    KRW_DKA("KRW-DKA", "디카르고", "dKargo"),
    KRW_SOLV("KRW-SOLV", "솔브 프로토콜", "Solv Protocol"),
    KRW_BLUE("KRW-BLUE", "블루핀", "Bluefin"),
    KRW_QKC("KRW-QKC", "쿼크체인", "QuarkChain"),
    KRW_HP("KRW-HP", "히포 프로토콜", "Hippo Protocol"),
    KRW_GAME2("KRW-GAME2", "게임빌드", "GameBuild"),
    KRW_ERA("KRW-ERA", "칼데라", "Caldera"),
    KRW_STRIKE("KRW-STRIKE", "스트라이크", "Strike"),
    KRW_ARDR("KRW-ARDR", "아더", "Ardor"),
    KRW_BOUNTY("KRW-BOUNTY", "체인바운티", "Chainbounty"),
    KRW_SHELL("KRW-SHELL", "마이쉘", "MyShell"),
    KRW_BERA("KRW-BERA", "베라체인", "Berachain"),
    KRW_PLUME("KRW-PLUME", "플룸", "Plume"),
    KRW_OBT("KRW-OBT", "오비터 파이낸스", "Orbiter Finance"),
    KRW_TRUMP("KRW-TRUMP", "오피셜 트럼프", "OFFICIAL TRUMP"),
    KRW_KERNEL("KRW-KERNEL", "커널 다오", "Kernel DAO"),
    KRW_COOKIE("KRW-COOKIE", "쿠키 다오", "Cookie DAO"),
    KRW_GNO("KRW-GNO", "노시스", "Gnosis"),
    KRW_VTHO("KRW-VTHO", "비토르 토큰", "VeThor Token"),
    KRW_ANIME("KRW-ANIME", "애니메코인", "Animecoin"),
    KRW_RED("KRW-RED", "레드스톤", "RedStone"),
    KRW_LAYER("KRW-LAYER", "솔레이어", "Solayer"),
    KRW_WCT("KRW-WCT", "월렛커넥트", "WalletConnect"),
    KRW_FLOCK("KRW-FLOCK", "플록", "FLock.io"),
    KRW_KAITO("KRW-KAITO", "카이토", "Kaito"),
    KRW_BMT("KRW-BMT", "버블맵스", "Bubblemaps"),
    KRW_C("KRW-C", "체인베이스 토큰", "Chainbase Token"),
    KRW_SOON("KRW-SOON", "쑨", "SOON"),
    KRW_PAXG("KRW-PAXG", "팍스골드", "PAX Gold"),
    KRW_AVL("KRW-AVL", "아발론", "Avalon"),
    KRW_B3("KRW-B3", "비쓰리", "B3"),
    KRW_PUNDIAI("KRW-PUNDIAI", "펀디에이아이", "Pundi AI"),
    KRW_ELX("KRW-ELX", "엘릭서", "Elixir"),
    KRW_COW("KRW-COW", "카우 프로토콜", "CoW Protocol"),
    KRW_WAL("KRW-WAL", "월러스", "Walrus"),
    KRW_BABY("KRW-BABY", "바빌론", "Babylon"),
    KRW_ES("KRW-ES", "이클립스", "Eclipse"),
    KRW_XTER("KRW-XTER", "엑스테리오", "Xterio"),
    KRW_NXPC("KRW-NXPC", "넥스페이스", "NEXPACE"),
    KRW_GRASS("KRW-GRASS", "그래스", "Grass"),
    KRW_ORCA("KRW-ORCA", "오르카", "Orca"),
    KRW_PUMP("KRW-PUMP", "펌프", "PUMP"),
    KRW_EPT("KRW-EPT", "밸런스", "Balance"),
    KRW_HAEDAL("KRW-HAEDAL", "해달 프로토콜", "Haedal Protocol"),
    KRW_AI16Z("KRW-AI16Z", "에이아이식스틴즈", "ai16z"),
    KRW_PARTI("KRW-PARTI", "파티클 네트워크", "Particle Network"),
    KRW_SXT("KRW-SXT", "스페이스 앤드 타임", "Space and Time"),
    KRW_PROMPT("KRW-PROMPT", "웨이파인더", "Wayfinder"),
    KRW_SIGN("KRW-SIGN", "사인", "Sign"),
    KRW_SAHARA("KRW-SAHARA", "사하라에이아이", "Sahara AI"),
    KRW_H("KRW-H", "휴머니티 프로토콜", "Humanity Protocol"),
    KRW_HOME("KRW-HOME", "디파이 앱", "Defi App"),
    KRW_OM("KRW-OM", "만트라", "MANTRA"),
    KRW_LA("KRW-LA", "라그랑주", "Lagrange"),
    KRW_SOPH("KRW-SOPH", "소폰", "Sophon"),
    KRW_HYPER("KRW-HYPER", "하이퍼레인", "Hyperlane"),
    KRW_FORT("KRW-FORT", "포르타", "Forta"),
    KRW_HUMA("KRW-HUMA", "후마 파이낸스", "Huma Finance"),
    KRW_SPK("KRW-SPK", "스파크", "Spark"),
    KRW_SYRUP("KRW-SYRUP", "메이플 파이낸스", "Maple Finance"),
    KRW_NEWT("KRW-NEWT", "뉴턴 프로토콜", "Newton Protocol"),
    KRW_RESOLV("KRW-RESOLV", "리졸브", "Resolv"),
    BTC_ETH("BTC-ETH", "이더리움", "Ethereum"),
    BTC_XRP("BTC-XRP", "엑스알피 [리플]", "XRP"),
    BTC_KAIA("BTC-KAIA", "카이아", "Kaia"),
    BTC_KSP("BTC-KSP", "클레이스왑", "KlaySwap Protocol"),
    BTC_DOGE("BTC-DOGE", "도지코인", "Dogecoin"),
    BTC_BNB("BTC-BNB", "비앤비", "BNB"),
    BTC_SOL("BTC-SOL", "솔라나", "Solana"),
    BTC_ENS("BTC-ENS", "이더리움네임서비스", "Ethereum Name Service"),
    BTC_CSPR("BTC-CSPR", "캐스퍼", "Casper"),
    BTC_WITCH("BTC-WITCH", "위치 토큰", "Witch Token"),
    BTC_TALK("BTC-TALK", "톡큰", "Talken"),
    BTC_DICE("BTC-DICE", "클레이다이스", "KLAYDICE"),
    BTC_AHT("BTC-AHT", "아하토큰", "AhaToken"),
    BTC_KWENTA("BTC-KWENTA", "크웬타", "Kwenta"),
    BTC_HVH("BTC-HVH", "하바", "HAVAH"),
    USDT_AMP("USDT-AMP", "앰프", "Amp");

    companion object {
        fun fromCode(code: String): Market? = values().find { it.code == code }
        fun fromKName(name: String): Market? = values().find { it.koreanName == name }
        fun fromUName(name: String): Market? = values().find { it.englishName == name }
    }
}